In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [8]:
print('1st element:', x[3])
print('1st element:', x[-3])
print('1st element:', x[-1])

1st element: 4
1st element: 3
1st element: 5


In [9]:
#changing a value of the array

x[2]= 18
print(x)

[ 1  2 18  4  5]


In [16]:
y = np.arange(3, 32, 2).reshape(5, 3)
print(y)

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]
 [21 23 25]
 [27 29 31]]


In [17]:
y[1,2]=42
print(y)

[[ 3  5  7]
 [ 9 11 42]
 [15 17 19]
 [21 23 25]
 [27 29 31]]


In [18]:
y[-2, -2]= 20
print(y)

[[ 3  5  7]
 [ 9 11 42]
 [15 17 19]
 [21 20 25]
 [27 29 31]]


In [19]:
#deleting element
h = np.array([1,2,3,4,5,6])
print(h)

h = np.delete(h, [1, 3])
print(h)

[1 2 3 4 5 6]
[1 3 5 6]


In [30]:
H = np.arange(2, 26, 3).reshape(4, 2)
print(H)

w = np.delete(H, 0, axis=1)
print("\n",w)

n = np.delete(H, 0, axis=0)
print("\n",n)

p = np.delete(H, 1, axis=0)
print("\n",p)


[[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]

 [[ 5]
 [11]
 [17]
 [23]]

 [[ 8 11]
 [14 17]
 [20 23]]

 [[ 2  5]
 [14 17]
 [20 23]]


In [34]:
b = np.delete(H, [0, 1], axis=1)
print("\n",b)


 []


In [36]:
#removes the the seconr(1) and third(2) rows in H
f = np.delete(H, [1, 2], axis=0)
print("\n",f)


 [[ 2  5]
 [20 23]]


In [37]:
#to add values
r = np.array([2,4,6,8])
print(r)

r = np.append(r, 3)
print(r)

[2 4 6 8]
[2 4 6 8 3]


In [38]:
r = np.append(r, [3, 9])
print(r)

[2 4 6 8 3 3 9]


In [39]:
H =np.append(H, [[12,14]], axis=0)
print(H)

[[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]
 [12 14]]


In [42]:
H =np.append(H, [[12],[14], [10], [11], [11]], axis=1)
print(H)

[[ 2  5 12]
 [ 8 11 14]
 [14 17 10]
 [20 23 11]
 [12 14 11]]


In [46]:
p =np.array([22, 43, 14, 52])
print(p)

p = np.insert(p, 2,[24, 10])
print("\n",p)

[22 43 14 52]

 [22 43 24 10 14 52]


In [56]:
pe = np.array([[1,5,2], [9, 0, 5]])
print(pe)

[[1 5 2]
 [9 0 5]]


In [57]:
pe = np.insert(pe, 1,[67,3,-5], axis=0)
print(pe)

[[ 1  5  2]
 [67  3 -5]
 [ 9  0  5]]


In [58]:
pe = np.insert(pe, 2,[17,-30,15], axis=1)
print(pe)

[[  1   5  17   2]
 [ 67   3 -30  -5]
 [  9   0  15   5]]


In [59]:
pe = np.insert(pe, 1,[[1],[0],[5]], axis=1)
print(pe)

[[  1   1   0   5   5  17   2]
 [ 67   1   0   5   3 -30  -5]
 [  9   1   0   5   0  15   5]]


## adding two elements together

In [61]:
yu = np.array([2, 5, 6])
wu = np.array([6,8,4])

print(yu,"\n\n", wu)

[2 5 6] 

 [6 8 4]


In [62]:
zu = np.vstack((yu, wu))
print(zu)

[[2 5 6]
 [6 8 4]]


In [63]:
zu = np.vstack((wu, yu))
print(zu)

[[6 8 4]
 [2 5 6]]


In [69]:
mu = np.hstack((wu.reshape(3,1), yu.reshape(3,1)))
print(mu)

[[6 2]
 [8 5]
 [4 6]]
